### ISSUE TITLE
Document the extension in gnome-pomodoro readme/website

### ISSUE THREAD

**Issue by codito** [gnome-pomodoro/gnome-pomodoro-tracking#13]
We should consider documenting the extension in gnome-pomodoro readme/website to make it more visible to end users :)

**Comment by josehbez** [comment]
> We should consider documenting the extension in gnome-pomodoro readme/website to make it more visible to end users :)

I send my PR  for website/readme

**Comment by sojusnik** [comment]
In the meantime this extensions could be also mentioned in the [readme of gnome-pomodoro](https://github.com/gnome-pomodoro/gnome-pomodoro) to have more exposure.
