### ISSUE TITLE
Adjust commands

### ISSUE THREAD

**Issue by sojusnik** [gnome-pomodoro/gnome-pomodoro-tracking#14]
You recommend to use `alias gp-tracking=gnome-pomodoro-tracking`, but the alias isn't permanent.

Therefore `gp-tracking -gps "$(state)" -gpt "$(triggers)" -gpd "$(duration)" -gpe "$(elapsed)"` doesn't work after a restart, only `gnome-pomodoro-tracking "$(state)" -gpt "$(triggers)" -gpd "$(duration)" -gpe "$(elapsed)"` does.

Can you either provide a command for a permanent alias or adjust the commands to `gnome-pomodoro-tracking` in the readme and the other instructions in order to prevent confusion?

**Comment by josehbez** [comment]
Thanks for the report. I've  started updating README
