### ISSUE TITLE
Allow adding tags and specify the default entry name

### ISSUE THREAD

**Issue by sojusnik** [gnome-pomodoro/gnome-pomodoro-tracking#17]
It would be helpful, if you could also specify a tag that will be added to an entry. This option could be added, when [configuring](https://github.com/gnome-pomodoro/gnome-pomodoro-tracking/blob/master/assets/toggl/README.md) a plugin.

By having a tag added to an entry, one could easily see all entries in Toggl, that were added by using Gnome-Pomodoro. This is useful, if one is not solely using Gnome-Pomodoro, but Toggl on other devices, as on Android, for example.

Defining the name of an entry, at the moment all entries are called `Pomodoro`, would also be useful.

**Comment by josehbez** [comment]
The last version the plugin Toggle support tags & each Pomodoro Stop not restart name, 

- [Docs Toggl](https://github.com/gnome-pomodoro/gnome-pomodoro-tracking/blob/master/docs/toggl.md)
- [Changelog](https://github.com/gnome-pomodoro/gnome-pomodoro-tracking/blob/master/.pm/changelog.yml#L24)

**Comment by sojusnik** [comment]
Just updated, adding tags now works, but what do you mean by?

> each Pomodoro Stop not restart name

**Comment by josehbez** [comment]
Before when you ran `gnome-pomodoro-tracking --name "Time Entry name"`, it would put the name of the current Pomodoro and when the timer finished it would remove the name of the entry and you had to rerun `gnome-pomodoro-tracking --name " Time Entry name "`.

In the new update you will only have to run once `gnome-pomodoro-tracking -n "Time Entry Name"` and use the name for future time entries.

> each Pomodoro Stop not restart name

**Comment by sojusnik** [comment]
Thanks for clarifying!
