### ISSUE TITLE
Toggl API is deprecated

### ISSUE THREAD

**Issue by sojusnik** [gnome-pomodoro/gnome-pomodoro-tracking#21]
Starting from yesterday, Toggl stopped working. After double-checking, it seems that the problem lies in the deprecated API:

```
$ gnome-pomodoro-tracking --plugin toggl
gnome-pomodoro-tracking --token XXX
"The V8 endpoint is scheduled to be shutdown on **23/05/2024**, this is a brownout. Please find the migration guide at https://engineering.toggl.com/changes/2022/10/01/api-v8-deprecation/index.html"
Traceback (most recent call last):
  File "/home/sojusnik/.local/pipx/venvs/gnome-pomodoro-tracking/lib/python3.12/site-packages/gnome_pomodoro_tracking/toggl.py", line 52, in auth
    raise Exception(req.text)
Exception: "The V8 endpoint is scheduled to be shutdown on 23/05/2024, this is a brownout. Please find the migration guide at https://engineering.toggl.com/changes/2022/10/01/api-v8-deprecation/index.html"
Fail auth check your token!
```
The [solution](https://engineering.toggl.com/changes/2022/10/01/api-v8-deprecation/index.html) is to move from API v8 to API v9, see also [here.](https://engineering.toggl.com/changes/) Could you have a look please?

**Comment by josehbez** [comment]
WIP

**Comment by josehbez** [comment]
Solved, please install latest version.

**Comment by josehbez** [comment]
> Installed the new version, but it's still not working. Although f.i. I can now access my projects through `gnome-pomodoro-tracking --projects` and `gnome-pomodoro-tracking --status` shows the correct information when a pomodoro is running, but after I stop a pomodoro, Toggl doesn't receive the data. Can you have a second look on it please?

Please install from `pip install -U git+https://github.com/gnome-pomodoro/gnome-pomodoro-tracking.git`, 

I have a problem publishing on pypi, I'm working on solving it.

**Comment by josehbez** [comment]
> With `git+https://github.com/gnome-pomodoro/gnome-pomodoro-tracking.git` it finally works, thanks!

Great, I finally  upgrade package at pypi.

**Comment by josehbez** [comment]
> Another thing that might be important: your animation shows that all three field (Pomodoro, Long Break, Short Break) in the settings should be enabled: https://github.com/gnome-pomodoro/gnome-pomodoro-tracking/blob/master/docs/img/gnome-pomodoro-settings.gif
> 
> But from my experience it was enough to only enable "Pomodoro" there, else after a Pomodoro stops, the timer will still be running, as shown in `gnome-pomodoro-tracking --status`. Can you clarify the proper setup please?


The animation is an example to capture all time blocks.
I am updating the guide and animation to leave only the minimum required.
