### ISSUE TITLE
Unable to use gnome-pomodoro-tracking command

### ISSUE THREAD

**Issue by billmdevs** [gnome-pomodoro/gnome-pomodoro-tracking#22]
When installing on Ubuntu 24.04 I get a `gnome-pomodoro-tracking: command not found` error.

Even after having installed it with  `python3.8 -m pip install -U gnome-pomodoro-tracking`

`pip3 install -U gnome-pomodoro-tracking` doesn't work directly on Ubuntu 24.04 with the error

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
```

**Comment by billmdevs** [comment]
Thank you very much! It can install now but the command `gnome-pomodoro-tracking`  doesn't work. When I lauch it or when I try to add a token or do anything else it says it's not found. Here is the error `gnome-pomodoro-tracking: command not found
`

**Comment by billmdevs** [comment]
I'm certain because in the issue you linked the command `gnome-pomodoro-tracking` works. It's just that the plugin auth is not working. In my case the command just doesn't work at all even if I don't place any arguments to it.

**Comment by josehbez** [comment]
Validate if your `$PATH` includes `$HOME/.local/bin` regularly installs to this location.

If it doesn't exist, add it using this command:
`echo 'export PATH=$HOME/.local/bin:$PATH' >> ~/.bashrc`

**Comment by billmdevs** [comment]
Perfect! Thank you very much Jose! That worked.

**Comment by billmdevs** [comment]
Nope! Everything is working alright when I try now.
